server:
  port: 8081

spring:
  application:
    name: gateway-server
  data:
    mongodb:
      authentication-database: admin
      database: gatewayserver
      host: localhost
      port: 27017
      username: devroot
      password: devroot

logging.level:
  com.bory: DEBUG
  root: DEBUG

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, refresh