version: '3.1'

services:
  mysql:
    container_name: mysql57
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=authserver
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--skip-character-set-client-handshake"]
    ports:
      - 3306:3306
    restart: always
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devroot
      - MONGO_INITDB_ROOT_PASSWORD=devroot
      - MONGO_INITDB_DATABASE=gatewayserver
    ports:
      - 27017:27017
